lib: [
  "_build/install/default/lib/Deck/Deck.a"
  "_build/install/default/lib/Deck/Deck.cma"
  "_build/install/default/lib/Deck/Deck.cmxa"
  "_build/install/default/lib/Deck/META"
  "_build/install/default/lib/Deck/card.ml"
  "_build/install/default/lib/Deck/deck.cmi"
  "_build/install/default/lib/Deck/deck.cmt"
  "_build/install/default/lib/Deck/deck.cmx"
  "_build/install/default/lib/Deck/deck.ml"
  "_build/install/default/lib/Deck/deck__Card.cmi"
  "_build/install/default/lib/Deck/deck__Card.cmt"
  "_build/install/default/lib/Deck/deck__Card.cmx"
  "_build/install/default/lib/Deck/deck__Features.cmi"
  "_build/install/default/lib/Deck/deck__Features.cmt"
  "_build/install/default/lib/Deck/deck__Features.cmx"
  "_build/install/default/lib/Deck/deck__Player.cmi"
  "_build/install/default/lib/Deck/deck__Player.cmt"
  "_build/install/default/lib/Deck/deck__Player.cmx"
  "_build/install/default/lib/Deck/deck__State.cmi"
  "_build/install/default/lib/Deck/deck__State.cmt"
  "_build/install/default/lib/Deck/deck__State.cmx"
  "_build/install/default/lib/Deck/dune-package"
  "_build/install/default/lib/Deck/features.ml"
  "_build/install/default/lib/Deck/opam"
  "_build/install/default/lib/Deck/player.ml"
  "_build/install/default/lib/Deck/state.ml"
]
libexec: [
  "_build/install/default/lib/Deck/Deck.cmxs"
]
doc: [
  "_build/install/default/doc/Deck/README.md"
]
